/*
Copyright Sahadat Hossain

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	shahinokacomv1alpha1 "github.com/shahincsejnu/extend-k8s-API-with-CRD/pkg/apis/shahin.oka.com/v1alpha1"
	versioned "github.com/shahincsejnu/extend-k8s-API-with-CRD/pkg/client/clientset/versioned"
	internalinterfaces "github.com/shahincsejnu/extend-k8s-API-with-CRD/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/shahincsejnu/extend-k8s-API-with-CRD/pkg/client/listers/shahin.oka.com/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// TeploymentInformer provides access to a shared informer and lister for
// Teployments.
type TeploymentInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.TeploymentLister
}

type teploymentInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewTeploymentInformer constructs a new informer for Teployment type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTeploymentInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredTeploymentInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredTeploymentInformer constructs a new informer for Teployment type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredTeploymentInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ShahinV1alpha1().Teployments(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ShahinV1alpha1().Teployments(namespace).Watch(context.TODO(), options)
			},
		},
		&shahinokacomv1alpha1.Teployment{},
		resyncPeriod,
		indexers,
	)
}

func (f *teploymentInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredTeploymentInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *teploymentInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&shahinokacomv1alpha1.Teployment{}, f.defaultInformer)
}

func (f *teploymentInformer) Lister() v1alpha1.TeploymentLister {
	return v1alpha1.NewTeploymentLister(f.Informer().GetIndexer())
}
