apiVersion: shahin.oka.com/v1
kind: Teployment
metadata:
  name: apiserver-teployment
  labels:
    app: apiserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apiserver
  template:
    metadata:
      labels:
        app: apiserver
    spec:
      containers:
        name: apiserver
        image: shahincsejnu/httpapiserver:v1.0.5
        ports:
          containerPort: 8080