apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: teployments.shahin.oka.com

scope: Namespaced
names:
  kind: Teployment
  plural: teployments
  singular: teployment
  shortNames:
    - teploy

spec:
  group: shahin.oka.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              replicas:
                type: integer
                format: int32
                minimum: 1
              selector:
                matchLabels:
                  app:
                    type: string
              template:
                metadata:
                  labels:
                    app:
                      type: string
                spec:
                  containers:
                    - name:
                        type: string
                      image:
                        type: string
                      ports:
                        - containerPort:
                            type: string
