apiVersion: shahin.oka.com/v1alpha1
kind: Teployment
metadata:
  name: apiserver-teployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apiserver
  serviceType: ClusterIP
  servicePorts:
    port: 8080
    targetPort: 8080
    #nodePort: 31005
  template:
    metadata:
      labels:
        app: apiserver
    spec:
      containers:
        name: apiserver
        image: shahincsejnu/httpapiserver:v1.0.5
        ports:
          containerPort: 8080