apiVersion: shahin.oka.com/v1alpha1
kind: Teployment
metadata:
  name: test3
spec:
  replicas: 3
  serviceType: NodePort
  nodePort: 31002
  label:
    test: test-label
  image: shahincsejnu/httpapiserver:v1.0.5
  containerPort: 8080