apiVersion: shahin.oka.com/v1alpha1
kind: Teployment
metadata:
  name: apiserver-teployment
spec:
  replicas: 1
  serviceType: NodePort
  image: shahincsejnu/httpapiserver:v1.0.5
  nodePort: 31005
  containerPort: 8080