/*
Copyright Sahadat Hossain

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/shahincsejnu/extend-k8s-API-with-CRD/pkg/apis/shahin.oka.com/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeTeployments implements TeploymentInterface
type FakeTeployments struct {
	Fake *FakeShahinV1alpha1
	ns   string
}

var teploymentsResource = schema.GroupVersionResource{Group: "shahin.oka.com", Version: "v1alpha1", Resource: "teployments"}

var teploymentsKind = schema.GroupVersionKind{Group: "shahin.oka.com", Version: "v1alpha1", Kind: "Teployment"}

// Get takes name of the teployment, and returns the corresponding teployment object, and an error if there is any.
func (c *FakeTeployments) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Teployment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(teploymentsResource, c.ns, name), &v1alpha1.Teployment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Teployment), err
}

// List takes label and field selectors, and returns the list of Teployments that match those selectors.
func (c *FakeTeployments) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.TeploymentList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(teploymentsResource, teploymentsKind, c.ns, opts), &v1alpha1.TeploymentList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.TeploymentList{ListMeta: obj.(*v1alpha1.TeploymentList).ListMeta}
	for _, item := range obj.(*v1alpha1.TeploymentList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested teployments.
func (c *FakeTeployments) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(teploymentsResource, c.ns, opts))

}

// Create takes the representation of a teployment and creates it.  Returns the server's representation of the teployment, and an error, if there is any.
func (c *FakeTeployments) Create(ctx context.Context, teployment *v1alpha1.Teployment, opts v1.CreateOptions) (result *v1alpha1.Teployment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(teploymentsResource, c.ns, teployment), &v1alpha1.Teployment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Teployment), err
}

// Update takes the representation of a teployment and updates it. Returns the server's representation of the teployment, and an error, if there is any.
func (c *FakeTeployments) Update(ctx context.Context, teployment *v1alpha1.Teployment, opts v1.UpdateOptions) (result *v1alpha1.Teployment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(teploymentsResource, c.ns, teployment), &v1alpha1.Teployment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Teployment), err
}

// Delete takes name of the teployment and deletes it. Returns an error if one occurs.
func (c *FakeTeployments) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(teploymentsResource, c.ns, name), &v1alpha1.Teployment{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeTeployments) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(teploymentsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.TeploymentList{})
	return err
}

// Patch applies the patch and returns the patched teployment.
func (c *FakeTeployments) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Teployment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(teploymentsResource, c.ns, name, pt, data, subresources...), &v1alpha1.Teployment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Teployment), err
}
